### ISSUE TITLE
Game crashes in newest 0.27.0 version

### ISSUE THREAD

**Issue by ghost** [portablejim/VeinMiner#25]
The game can't load. I've tried adding it in MULTIPLE modpacks. Attached is the log. Just FYI I can go back the to the 26.1 version and it works fine.

[10:39:38] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[10:39:38] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[10:39:38] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[10:39:38] [main/INFO] [FML]: Forge Mod Loader version 7.10.113.1381 for Minecraft 1.7.10 loading
[10:39:38] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 7:amd64:6.1, installed at C:\Users\stephanie7\Documents\Curse\Minecraft\Install\runtime\jre-x64\1.8.0_25
[10:39:38] [main/INFO] [FML]: [AppEng] Core Init
[10:39:38] [main/WARN] [FML]: The coremod aroma1997.core.coremod.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:39:38] [main/WARN] [FML]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
Downloading file http://files.minecraftforge.net/maven/codechicken/CodeChickenLib/1.7.10-1.1.3.134//CodeChickenLib-1.7.10-1.1.3.134-universal.jar
[10:39:39] [main/INFO] [STDOUT]: [codechicken.core.launch.DepLoader$DepLoadInst:download:343]: Download complete
[10:39:39] [main/INFO] [STDERR]: [codechicken.core.launch.DepLoader$DepLoadInst:checkExisting:436]: Warning: version of ForgeMultipart, 1.1.2.331 is newer than request 1.1.0.309
Downloading file https://dl.dropboxusercontent.com/s/m632g4c09vypj82/LibSandstone-1.0.0.jar
[10:39:41] [main/INFO] [STDOUT]: [codechicken.core.launch.DepLoader$DepLoadInst:download:343]: Download complete
Downloading file https://dl.dropboxusercontent.com/u/47135879//Baubles-1.7.10-1.0.1.10.jar
[10:39:41] [main/INFO] [STDOUT]: [codechicken.core.launch.DepLoader$DepLoadInst:download:343]: Download complete
[10:39:41] [main/WARN] [FML]: The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:39:41] [main/WARN] [FML]: The coremod fastcraft.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:39:41] [main/ERROR] [FML]: Unable to read the jar file ForgeMultipart-1.7.10-1.1.2.331-universal.jar - ignoring
java.io.FileNotFoundException: C:\Users\stephanie7\Documents\Curse\Minecraft\Instances\Einherjar\mods\ForgeMultipart-1.7.10-1.1.2.331-universal.jar (The system cannot find the file specified)
    at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_25]
    at java.util.zip.ZipFile.<init>(ZipFile.java:220) ~[?:1.8.0_25]
    at java.util.zip.ZipFile.<init>(ZipFile.java:150) ~[?:1.8.0_25]
    at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_25]
    at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_25]
    at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:265) [forge-1.7.10-10.13.3.1381-1.7.10.jar:?]
    at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214) [forge-1.7.10-10.13.3.1381-1.7.10.jar:?]
    at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.3.1381-1.7.10.jar:?]
    at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.3.1381-1.7.10.jar:?]
    at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.3.1381-1.7.10.jar:?]
    at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.3.1381-1.7.10.jar:?]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[10:39:41] [main/WARN] [FML]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:39:41] [main/WARN] [FML]: The coremod logisticspipes.asm.LogisticsPipesCoreLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:39:41] [main/WARN] [FML]: The coremod net.malisis.core.asm.MalisisCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:39:41] [main/WARN] [FML]: The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:39:41] [main/WARN] [FML]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:39:41] [main/WARN] [FML]: The coremod openblocks.OpenBlocksCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:39:41] [main/WARN] [FML]: The coremod openmods.core.OpenModsCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:39:42] [main/WARN] [FML]: The coremod lumien.randomthings.Transformer.RTLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:39:42] [main/WARN] [FML]: The coremod com.dynious.refinedrelocation.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:39:42] [main/WARN] [FML]: The coremod xreliquary.common.asm.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:39:42] [main/WARN] [FML]: The coremod stevesaddons.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:39:42] [main/WARN] [FML]: The coremod thaumcraft.codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:39:42] [main/WARN] [FML]: The coremod thaumic.tinkerer.preloader.ThaumicTLoaderContainer does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:39:42] [main/WARN] [FML]: The coremod portablejim.veinminer.asm.VeinMinerCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:39:42] [main/WARN] [FML]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:39:42] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[10:39:42] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[10:39:42] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[10:39:42] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[10:39:42] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:39:42] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:39:42] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[10:39:42] [main/ERROR] [FML]: The minecraft jar file:/C:/Users/stephanie7/Documents/Curse/Minecraft/Install/versions/forge-10.13.3.1381/forge-10.13.3.1381.jar!/net/minecraft/client/ClientBrandRetriever.class appears to be corrupt! There has been CRITICAL TAMPERING WITH MINECRAFT, it is highly unlikely minecraft will work! STOP NOW, get a clean copy and try again!
[10:39:42] [main/ERROR] [FML]: FML has been ordered to ignore the invalid or missing minecraft certificate. This is very likely to cause a problem!
[10:39:42] [main/ERROR] [FML]: Technical information: ClientBrandRetriever was at jar:file:/C:/Users/stephanie7/Documents/Curse/Minecraft/Install/versions/forge-10.13.3.1381/forge-10.13.3.1381.jar!/net/minecraft/client/ClientBrandRetriever.class, there were 0 certificates for it
[10:39:42] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:39:42] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:39:42] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:39:42] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:39:42] [main/INFO] [Aroma1997Core]: Finished data injection.
[10:39:42] [main/INFO] [Aroma1997Core]: Finished data injection.
[10:39:42] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:39:43] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:39:43] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:39:43] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:39:43] [main/INFO] [INpurePreloader]: Attempting to detect JVM version...
[10:39:43] [main/INFO] [INpurePreloader]: Detected JVM: 1.8
[10:39:43] [main/INFO] [INpurePreloader]: Starting library configuration...
[10:39:43] [main/INFO] [STDOUT]: [info.inpureprojects.core.API.Utils.Downloader:download:19]: Downloading: http://files.inpureprojects.info/libs/commons-codec-1.9.jar
[10:39:44] [main/INFO] [STDOUT]: [info.inpureprojects.core.API.Utils.Downloader:download:19]: Downloading: http://files.inpureprojects.info/libs/commons-compress-1.8.1.jar
[10:39:45] [main/INFO] [INpureLogInterceptor]: System attached to FML. Now intercepting all logging calls.
[10:39:45] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:39:45] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:39:45] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:39:45] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:getASMTransformerClass:102]: Successfully Registered Transformer
[10:39:45] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:295]: [Micdoodle8Core]: Patching game...
[10:39:45] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:295]: [Micdoodle8Core]: Patching game...
[10:39:45] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:39:45] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:39:45] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:39:45] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:39:45] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:39:45] [main/INFO] [STDERR]: [xreliquary.common.asm.DepLoader$DepLoadInst:checkExisting:433]: Warning: version of ForgeMultipart, 1.1.2.331 is newer than request 1.1.0.309
[10:39:45] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:39:45] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:39:45] [main/INFO] [STDERR]: [thaumcraft.codechicken.core.launch.DepLoader$DepLoadInst:checkExisting:459]: Warning: version of ForgeMultipart, 1.1.2.331 is newer than request 1.1.0.309
[10:39:45] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:39:45] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:39:45] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:39:45] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:39:45] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:39:45] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:39:45] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[10:39:45] [main/INFO] [STDOUT]: [cofh.asm.CoFHAccessTransformer:readMappingFile:40]: Adding Accesstransformer map: CoFH_at.cfg
[10:39:46] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:39:46] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:39:46] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:39:46] [main/INFO] [malisiscore]: [MalisisCoreTransformer] Hook registered for net.minecraft.client.Minecraft
[10:39:46] [main/INFO] [malisiscore]: [MalisisCoreTransformer] Hook registered for net.minecraft.client.multiplayer.PlayerControllerMP
[10:39:46] [main/INFO] [malisiscore]: [ChunkBlockTransformer] Hook registered for net.minecraft.world.chunk.Chunk
[10:39:46] [main/INFO] [malisiscore]: [ChunkCollisionTransformer] Hook registered for net.minecraft.world.World
[10:39:46] [main/INFO] [malisiscore]: [ChunkCollisionTransformer] Hook registered for net.minecraft.world.World
[10:39:46] [main/INFO] [malisiscore]: [ChunkCollisionTransformer] Hook registered for net.minecraft.item.ItemBlock
[10:39:46] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:39:46] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:39:46] [main/INFO] [STDOUT]: [alexiil.mods.load.Translation:<init>:134]: Found an invalid line ()
[10:39:46] [main/INFO] [STDOUT]: [alexiil.mods.load.Translation:<init>:134]: Found an invalid line ()
[10:39:46] [main/INFO] [STDOUT]: [alexiil.mods.load.Translation:<init>:134]: Found an invalid line ()
[10:39:46] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[10:39:46] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[10:39:46] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[10:39:46] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[10:39:46] [main/INFO] [malisiscore]: Found hooks for net.minecraft.client.Minecraft (bao)
[10:39:46] [main/INFO] [STDOUT]: [alexiil.mods.load.coremod.BetterLoadingScreenTransformer:transformMinecraft:110]: Transformed Minecraft
[10:39:46] [main/INFO] [malisiscore]: Found hooks for net.minecraft.world.World (ahb)
[10:39:46] [main/INFO] [RandomThingsCore]: Found World Class: net/minecraft/world/World
[10:39:46] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1763]: Galacticraft successfully injected bytecode into: sv (1 / 1)
[10:39:46] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1763]: Galacticraft successfully injected bytecode into: sa (1 / 1)
[10:39:46] [main/INFO] [FML]: [OpenBlocks] Trying to patch EntityPlayer.isInBed (class: yz)
[10:39:46] [main/INFO] [FML]: [OpenBlocks] isInBed patch applied. Enabling sleeping bags
[10:39:46] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1763]: Galacticraft successfully injected bytecode into: bdi (1 / 1)
[10:39:46] [main/INFO] [STDOUT]: [brad16840.common.asm.ClassTransformer:patchGuiContainer:204]: Backpacks! has patched GuiContainer to allow its backpacks to be opened from vanilla guis
[10:39:46] [main/INFO] [AE2-CORE]: func_146977_a(Lnet/minecraft/inventory/Slot;)V - Transformed
[10:39:46] [main/INFO] [AE2-CORE]: func_146977_a_original(Lnet/minecraft/inventory/Slot;)V - New Method
[10:39:46] [main/INFO] [AE2-CORE]: func_146977_a(Lnet/minecraft/inventory/Slot;)V - Invoke Virtual
[10:39:46] [main/INFO]: Setting user: StephJ2Fan
[10:39:47] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1763]: Galacticraft successfully injected bytecode into: xk (1 / 1)
[10:39:47] [main/INFO] [RandomThingsCore]: Found Item Class: net/minecraft/item/Item
[10:39:47] [main/INFO] [FastLeafDecay]: Patching leaves.
[10:39:47] [main/INFO] [FastLeafDecay]: Found Leave Class: net/minecraft/block/BlockLeavesBase
[10:39:47] [main/INFO] [RandomThingsCore]: Found Leave Class: net/minecraft/block/BlockLeavesBase
[10:39:47] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/block/BlockOldLeaf
    at net.minecraft.block.Block.func_149671_p(Block.java:222) ~[aji.class:?]
    at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
    at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
    ... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.block.BlockOldLeaf
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
    at net.minecraft.block.Block.func_149671_p(Block.java:222) ~[aji.class:?]
    at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
    at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
    ... 6 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/block/BlockLeaves
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_25]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_25]
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
    at net.minecraft.block.Block.func_149671_p(Block.java:222) ~[aji.class:?]
    at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
    at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
    ... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.block.BlockLeaves
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_25]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_25]
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
    at net.minecraft.block.Block.func_149671_p(Block.java:222) ~[aji.class:?]
    at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
    at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
    ... 6 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/block/BlockLeavesBase
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_25]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_25]
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_25]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_25]
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
    at net.minecraft.block.Block.func_149671_p(Block.java:222) ~[aji.class:?]
    at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
    at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
    ... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.block.BlockLeavesBase
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_25]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_25]
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_25]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_25]
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
    at net.minecraft.block.Block.func_149671_p(Block.java:222) ~[aji.class:?]
    at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
    at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
    ... 6 more
Caused by: java.lang.ClassFormatError: Duplicate method name&signature in class file net/minecraft/block/BlockLeavesBase
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_25]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_25]
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_25]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_25]
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_25]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_25]
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
    at net.minecraft.block.Block.func_149671_p(Block.java:222) ~[aji.class:?]
    at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:355) ~[kl.class:?]
    at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
    ... 6 more

**Comment by portablejim** [comment]
If it's still an issue create a new bug report. This may have been fixed but is now old.
