### ISSUE TITLE
VeinMiner crash using AOE tools

### ISSUE THREAD

**Issue by dvhaldane** [portablejim/VeinMiner#65]
When using tools with AOE such as Draconic Pick, ExCompressum, Tinkers, etc.  the server stalls in an endless loop.

Adding in Draconic Pick as a special snowflake tool has no effect:

ompressum:doubleCompressedDiamondHammer], [excompressum:compressedCrook]]
    S:special_snowflake_tools <
        DraconicEvolution:draconicPickaxe
     >
}

Any help would be appreciated.

Stall excerpt below:

"Server thread" #22 prio=5
RUNNABLE
    at sun.reflect.Reflection.getCallerClass(Native Method)
    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.logging.log4j.core.impl.ReflectiveCallerClassUtility.getCaller(ReflectiveCallerClassUtility.java:150)
    at org.apache.logging.log4j.core.impl.ThrowableProxy.getCurrentStack(ThrowableProxy.java:333)
    at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:96)
    at org.apache.logging.log4j.core.impl.Log4jLogEvent.<init>(Log4jLogEvent.java:114)
    at org.apache.logging.log4j.core.impl.Log4jLogEvent.<init>(Log4jLogEvent.java:90)
    at org.apache.logging.log4j.core.impl.DefaultLogEventFactory.createEvent(DefaultLogEventFactory.java:49)
    at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:365)
    at org.apache.logging.log4j.core.Logger.log(Logger.java:110)
    at org.apache.logging.log4j.spi.AbstractLogger.log(AbstractLogger.java:1448)
    at cpw.mods.fml.relauncher.FMLRelaunchLog.log(FMLRelaunchLog.java:83)
    at cpw.mods.fml.common.FMLLog.log(FMLLog.java:40)
    at cpw.mods.fml.common.eventhandler.EventBus.handleException(EventBus.java:154)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:145)
    at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:481)
    at com.brandon3055.draconicevolution.common.items.tools.baseclasses.MiningTool.breakExtraBlock(MiningTool.java:219)
    at com.brandon3055.draconicevolution.common.items.tools.baseclasses.MiningTool.breakAOEBlocks(MiningTool.java:178)
    at com.brandon3055.draconicevolution.common.items.tools.baseclasses.MiningTool.onBlockStartBreak(MiningTool.java:74)
    at net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:327)
    at portablejim.veinminer.core.MinerInstance.mineBlock(MinerInstance.java:286)
    at portablejim.veinminer.core.MinerInstance.mineBlock(MinerInstance.java:274)
    at portablejim.veinminer.core.CoreEvents.blockBreakEvent(CoreEvents.java:40)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_364_CoreEvents_blockBreakEvent_BreakEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:481)
    at com.brandon3055.draconicevolution.common.items.tools.baseclasses.MiningTool.breakExtraBlock(MiningTool.java:219)
    at com.brandon3055.draconicevolution.common.items.tools.baseclasses.MiningTool.breakAOEBlocks(MiningTool.java:178)
    at com.brandon3055.draconicevolution.common.items.tools.baseclasses.MiningTool.onBlockStartBreak(MiningTool.java:74)
    at net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:327)
    at portablejim.veinminer.core.MinerInstance.mineBlock(MinerInstance.java:286)
    at portablejim.veinminer.core.MinerInstance.mineBlock(MinerInstance.java:274)
    at portablejim.veinminer.core.CoreEvents.blockBreakEvent(CoreEvents.java:40)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_364_CoreEvents_blockBreakEvent_BreakEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)

**Comment by SonnyX** [comment]
src/main/java/portablejim/veinminer/core/CoreEvents.java:46
+if(event.getPlayer() instanceof net.minecraft.client.entity.EntityClientPlayerMP) return;

That should fix these kind of issues I believe, atleast fixes my issues in SkyFactory 2.5.3

**Comment by Jakja2** [comment]
@SonnyX Can you post the line above this line? My line numbers may be different than yours.

**Comment by SonnyX** [comment]
It would go inbetween the next two lines:
           blockLimit = Math.min(startConfig.blockLimit, blockLimit);
            MinerInstance instance = new MinerInstance(event.world, (EntityPlayerMP) event.getPlayer(), Compatibility.getPoint(event), new BlockID(Block.blockRegistry.getNameForObject(event.block), event.blockMetadata), server, radiusLimit, blockLimit);

**Comment by Jakja2** [comment]
@SonnyX Adding `+if(event.getPlayer() instanceof net.minecraft.client.entity.EntityClientPlayerMP) return;` seems to give java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityClientPlayerMP

I've tried changing it to `if(event.getPlayer() instanceof net.minecraft.entity.player.EntityPlayerMP) return;` which I think is what you meant. When I insert that between the two lines you posted and load it onto a server, veinminer seems to stop working. It loads fine, but it doesn't veinmine. Any idea on how to fix this?

**Comment by SonnyX** [comment]
Hehe, nice change :')
`if(event.getPlayer() instanceof net.minecraft.client.entity.EntityClientPlayerMP) return;`
No this line was to prevent client sided crashes by checking if the player which was passed to the MinerInstance wasn't a client sided player, which would cause an error with a stacktrace resulting in the client to shut down. I do have to say that this fix isn't a server stalling fix, this only resolves client sided issues (Tinker's AOE Tools).

Using my fix on a dedicated server would therefor also be useless and indeed result in a class not found exception, it got quite late last night and this thread seemed like the same problem at the first glance.

I'm gonna see if I can find something that would cause a stall in the server when using AOE tools.

**Comment by Jakja2** [comment]
Oh, I see. Would you happen to know how to fix the issue of the server stalling?

**Comment by SonnyX** [comment]
Ah, it is probably trying to break air to be honest.
Did you also to manage to get this exception on the server?
If so please copy it here and note down which version of minecraft and veinminer you are using.

**Comment by Jakja2** [comment]
Using minecraft version 1.7.10 and veinminer 0.33.0 986afb0

Let me load up a server to get the error, one second.

Edit: Here's the error http://pastebin.com/uTWbDiaa

**Comment by SonnyX** [comment]
See if this fixes the problem:
http://pastebin.com/kPDkz805

**Comment by Jakja2** [comment]
Same error with that. 

> at portablejim.veinminer.core.MinerInstance.mineBlock(MinerInstance.java:275) ~[MinerInstance.class:?]
> `return mineBlock(point.getX(), point.getY(), point.getZ());`
> 
>   at portablejim.veinminer.core.MinerInstance.mineBlock(MinerInstance.java:289) ~[MinerInstance.class:?]
> `boolean success = player.theItemInWorldManager.tryHarvestBlock(x, y, z);`
> 
>   at portablejim.veinminer.core.CoreEvents.blockBreakEvent(CoreEvents.java:44) ~[CoreEvents.class:?]
> `if (instance.mineBlock(breakPont) > 0) {`

**Comment by SonnyX** [comment]
Now I am going to suggest something insanely stupid:
add this:
`System.out.println("Trying to harvest block: " + newBlock.name);`
just before:
`boolean success = player.theItemInWorldManager.tryHarvestBlock(x, y, z);`

Then run the server and make it crash again, see what block it tries to harvest last before it crashes.

**Comment by Jakja2** [comment]
Interesting...

I did veinminer with a regular, non-aoe, pickaxe and it gave me `[portablejim.veinminer.core.MinerInstance:mineBlock:289]: Trying to harvest block: minecraft:stone`

When I tried veinminer with a draconic pickaxe, aoe enabled, it gave me `[portablejim.veinminer.core.MinerInstance:mineBlock:289]: Trying to harvest block: minecraft:cobblestone`

The weird thing is that I was mining regular stone both times.

It spammed these message quite a few times.

**Comment by SonnyX** [comment]
Hehe, I do believe you when you say it spams it a lot, thats why I said it was an insanely stupid as it may crash minecraft before the crash happens :)
It somehow is an issue only for Draconic tools though I believe.
Have you tried with another AOE tool so far (non Draconic)?

**Comment by Jakja2** [comment]
I've tried with the Tinker's construct hammer and the same thing happens.

**Comment by Jakja2** [comment]
I'm pretty sure it broke when the veinminer event stuff was rewritten (5b382ce). Version 0.31.6 of veinminer worked with aoe tools, but the next updates don't.

**Comment by SonnyX** [comment]
Hmm because of the AOE effect the blocks get double added to the QueQue it seems (times 8 per cycle or so), making it repeat itself exponentially depending on the amount of blocks mined.
Somewhere draconic tools catches that VeinMiner broke the block (through code injection ofcourse) and decide to break the blocks around them.

**Comment by Jakja2** [comment]
I went to look back before the veinminer event was re-written and realized that the problem occurred then too. The only thing that is different is that after it was re-written, it crashes the server.

When AOE tools are used each block that is destroyed gets a new minerInstance created for it. Could you think of an easy way to change it to just the block that was first targeted and not each block that was broken would have an instance created?

**Comment by SonnyX** [comment]
To be honest: Yes, an easy change would be to bind an MinerInstance to a player instead of to a block, therefor only one MinerInstance would be allowed at a time.

**Comment by SonnyX** [comment]
To be honest: Yes, an easy change would be to bind an MinerInstance to a player instead of to a block, therefor only one MinerInstance would be allowed at a time.

Let me fork this repository and test that real quick.

**Comment by SonnyX** [comment]
@Jakja2 If you want to prevent crash you should compile the sourcecode at my github for now, it should prevent a crash, you might (REALLY) want to take out the System.out.println messages in the three following files:
MinerServer
CoreEvents
MinerInstance

Don't know why it won't break the blocks just yet.

**Comment by Jakja2** [comment]
Reading through it real quick. Sorry, just woke up.

**Comment by Jakja2** [comment]
@SonnyX Even with that some weird things happen with draconic tools. I've been trying to make it so that draconic tools are blacklisted from veinminer, but I'm not very good at coding. Would you be able to help me?

**Comment by Mithril7** [comment]
Any updates on this?

**Comment by portablejim** [comment]
Should be fixed. Please test.
