### ISSUE TITLE
Crash in new GUI config

### ISSUE THREAD

**Issue by tecnobrat** [portablejim/VeinMiner#8]
I clicked on tool list for pickaxes.

```
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 7/17/14 5:10 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
    at net.minecraft.item.ItemStack.func_77964_b(ItemStack.java:219)
    at portablejim.veinminer.configuration.client.elements.GuiElementSlotItemlist.drawSlot(GuiElementSlotItemlist.java:99)
    at cpw.mods.fml.client.GuiScrollingList.drawScreen(GuiScrollingList.java:324)
    at portablejim.veinminer.configuration.client.ItemlistConfigGuiScreen.func_73863_a(ItemlistConfigGuiScreen.java:185)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:945)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:835)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:273)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:363)
    at org.multimc.EntryPoint.listen(EntryPoint.java:165)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at net.minecraft.item.ItemStack.func_77964_b(ItemStack.java:219)
    at portablejim.veinminer.configuration.client.elements.GuiElementSlotItemlist.drawSlot(GuiElementSlotItemlist.java:99)
    at cpw.mods.fml.client.GuiScrollingList.drawScreen(GuiScrollingList.java:324)
    at portablejim.veinminer.configuration.client.ItemlistConfigGuiScreen.func_73863_a(ItemlistConfigGuiScreen.java:185)

-- Screen render details --
Details:
    Screen name: portablejim.veinminer.configuration.client.ItemlistConfigGuiScreen
    Mouse location: Scaled: (250, 198). Absolute: (1002, 226)
    Screen size: Scaled: (480, 255). Absolute: (1920, 1017). Scale factor of 4
Stacktrace:
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:945)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:835)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:273)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:363)
    at org.multimc.EntryPoint.listen(EntryPoint.java:165)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Windows 8 (amd64) version 6.2
    Java Version: 1.7.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 318278232 bytes (303 MB) / 770703360 bytes (735 MB) up to 954728448 bytes (910 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.03 FML v7.2.217.1161 Minecraft Forge 10.12.2.1161 48 mods loaded, 48 mods active
    mcp{9.03} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    FML{7.2.217.1161} [Forge Mod Loader] (forge-1.7.2-10.12.2.1161-mc172.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    Forge{10.12.2.1161} [Minecraft Forge] (forge-1.7.2-10.12.2.1161-mc172.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    AppliedEnergistics2-Core{rv0-stable-9} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    CodeChickenCore{1.0.2.10} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    ImmibisMicroblocks{58.1.5} [Immibis's Microblocks] (immibis-microblocks-58.1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    MobiusCore{1.2.2} [MobiusCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    NotEnoughItems{1.0.2.14} [Not Enough Items] (NotEnoughItems-1.7.2-1.0.2.14-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    TConstruct-Preloader{0.1.1} [Tinkers Corestruct] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    VeinMiner_coremod{null_build-null} [Core mod] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    bspkrsCore{6.11} [bspkrsCore] ([1.7.2]bspkrsCore-universal-6.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    ArmorStatusHUD{1.26} [ArmorStatusHUD] ([1.7.2]ArmorStatusHUD-client-1.26.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    StartingInventory{1.7.2.r03} [StartingInventory] ([1.7.2]StartingInventory-universal-1.7.2.r03.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    BuildCraft|Core{5.0.6} [BuildCraft] (buildcraft-5.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    appliedenergistics2{rv0-stable-9} [Applied Energistics 2] (appliedenergistics2-rv0-stable-9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    Waila{1.5.2_1.7.2} [Waila] (Waila-1.5.2a_1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    ae2tech{0.1-b60} [AE2 Tech Add-On] (AE2TechAddOn-1.7.2-0.1-b60-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    BiblioCraft{1.7.1} [BiblioCraft] (BiblioCraft[1.7.1][MC1.7.2].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    BuildCraft|Builders{5.0.6} [BC Builders] (buildcraft-5.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    BuildCraft|Energy{5.0.6} [BC Energy] (buildcraft-5.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    BuildCraft|Factory{5.0.6} [BC Factory] (buildcraft-5.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    BuildCraft|Transport{5.0.6} [BC Transport] (buildcraft-5.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    BuildCraft|Silicon{5.0.6} [BC Silicon] (buildcraft-5.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    CarpentersBlocks{3.2.4} [Carpenter's Blocks] (Carpenter's Blocks v3.2.4 - MC 1.7+.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    chisel{1.5.4g} [Chisel] (Chisel-1.7.2-1.5.4g.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    ImmibisCore{58.1.4} [Immibis Core] (immibis-core-58.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    DimensionalAnchors{58.1.3} [Dimensional Anchors] (dimensional-anchor-58.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    EnderIO{2.0_beta} [Ender IO] (enderio-2.0_beta.123.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    EnderStorage{1.4.4.8} [EnderStorage] (EnderStorage-1.7.2-1.4.4.8-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    exnihilo{1.33} [Ex Nihilo] (Ex-Nihilo-1.33 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    extracells{2.1.3} [ExtraCells] (ExtraCells-2.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    ExtraUtilities{1.1.0b} [Extra Utilities] (extrautilities-1.1.0b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    inventorytweaks{1.58-dev-121} [Inventory Tweaks] (InventoryTweaks-1.58-dev-121.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    IronChest{6.0.36.725} [Iron Chest] (ironchest-1.7.2-6.0.36.725-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    JABBA{1.1.4} [JABBA] (Jabba-1.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    Mantle{1.7.2-149.5b27d20} [Mantle] (Mantle-1.7.2-149.5b27d20.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    Natura{2.2.0} [Natura] (natura-1.7.2-45.26fd68b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    NEIAddons{1.11.0.4} [NEI Addons] (neiaddons-mc172-1.11.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    NEIAddons|ExtraBees{1.11.0.4} [NEI Addons: Extra Bees] (neiaddons-mc172-1.11.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    NEIAddons|Forestry{1.11.0.4} [NEI Addons: Forestry] (neiaddons-mc172-1.11.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    NEIAddons|CraftingTables{1.11.0.4} [NEI Addons: Crafting Tables] (neiaddons-mc172-1.11.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    NEIAddons|ExNihilo{1.11.0.4} [NEI Addons: Ex Nihilo] (neiaddons-mc172-1.11.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    MapWriter{2.1.1} [MapWriter] (Opis-1.2.2a_1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    Opis{1.2.2a} [Opis] (Opis-1.2.2a_1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    TConstruct{1.7.2-1.6.0.jenkins500} [Tinkers' Construct] (TConstruct-1.7.2-1.6.0.jenkins500.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    VeinMiner{0.16.1} [Vein Miner] (VeinMiner-1.7.10_0.16.1.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    VeinMinerModSupport{0.16.1} [Mod Support] (VeinMiner-1.7.10_0.16.1.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    YUNoMakeGoodMap{3.0} [YUNoMakeGoodMap] (YUNoMakeGoodMap-1.7.2-4.0.0.10-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
    AE2 Version: stable rv0-stable-9 for Forge 10.12.1.1060
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    AE2 Integration: RotaryCraft:OFF, IC2:OFF, RC:OFF, BC:ON, MJ5:ON, MJ6:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, Waila:ON, CLApi:OFF, RB:OFF, InvTweaks:ON, NEI:ON, CraftGuide:OFF, FMP:OFF
    Launched Version: 1.7.2
    LWJGL: 2.9.1
    OpenGL: GeForce GTX 760/PCIe/SSE2 GL version 4.4.0, NVIDIA Corporation
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: [Faithful.zip]
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: ~~ERROR~~ NullPointerException: null
    Anisotropic Filtering: Off (1)

```

**Comment by tecnobrat** [comment]
Here is my config: https://gist.github.com/tecnobrat/8a98298016837ba42de7

**Comment by tecnobrat** [comment]
If I was going to guess, its because I have `exnihilo:hammer` in the S:itemList.pickaxe list, which I do not believe is a valid tool.
