### ISSUE TITLE
Crash Exception loop - TConstruct Hammer

### ISSUE THREAD

**Issue by xorinzor** [portablejim/VeinMiner#90]
Related to #65 

Our server ends up in a crash exception loop when a TConstruct Hammer is used, has been crashing multiple times a day now, would very much appreciate a way to fix this (perhaps a config option?)

Using veinminer 0.34 - R473

```
java.lang.StackOverflowError: Exception in server tick loop
	at java.security.AccessController.doPrivileged(Native Method)
	at java.lang.ClassLoader.checkPackageAccess(ClassLoader.java:500)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:146)
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:482)
	at tconstruct.library.tools.HarvestTool.breakExtraBlock(HarvestTool.java:275)
	at tconstruct.library.tools.AOEHarvestTool.onBlockStartBreak(AOEHarvestTool.java:77)
	at net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:329)
	at portablejim.veinminer.core.MinerInstance.mineBlock(MinerInstance.java:286)
	at portablejim.veinminer.core.MinerInstance.mineBlock(MinerInstance.java:274)
	at portablejim.veinminer.core.CoreEvents.blockBreakEvent(CoreEvents.java:48)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_496_CoreEvents_blockBreakEvent_BreakEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:482)
	at tconstruct.library.tools.HarvestTool.breakExtraBlock(HarvestTool.java:275)
	at tconstruct.library.tools.AOEHarvestTool.onBlockStartBreak(AOEHarvestTool.java:77)
	at net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:329)
	at portablejim.veinminer.core.MinerInstance.mineBlock(MinerInstance.java:286)
	at portablejim.veinminer.core.MinerInstance.mineBlock(MinerInstance.java:274)
	at portablejim.veinminer.core.CoreEvents.blockBreakEvent(CoreEvents.java:48)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_496_CoreEvents_blockBreakEvent_BreakEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:482)
	at tconstruct.library.tools.HarvestTool.breakExtraBlock(HarvestTool.java:275)
	at tconstruct.library.tools.AOEHarvestTool.onBlockStartBreak(AOEHarvestTool.java:77)
	at net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:329)
-- etc --
```

**Comment by portablejim** [comment]
Should be fixed. Please test.
